ISP_PREFIX ?= $(HOME)/.local/isp/

libbsp-%: %
	$(MAKE) -C $< -f Makefile.bsp libbsp

install-%: % libbsp-%
	$(MAKE) -C $< -f Makefile.bsp install

clean-%: %
	$(MAKE) -C $< -f Makefile.bsp clean

libbsp: libbsp-hifive

install: install-hifive

clean: clean-hifive